apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: client-master
spec:
  selector:
    matchLabels:
      app: client
      role: master
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: client
        role: master
        tier: backend
    spec:
      containers:
      - name: master
        image: hamaro/multi-client
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 6379
