apiVersion: v1
kind: Service
metadata:
  name: server-master
  labels:
    app: server
    role: master
    tier: backend
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: server
    role: master
    tier: backend
