apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: worker-slave
spec:
  selector:
    matchLabels:
      app: worker
      role: slave
      tier: backend
  replicas: 2
  template:
    metadata:
      labels:
        app: worker
        role: slave
        tier: backend
    spec:
      containers:
      - name: slave
        image: hamaro/multi-worker
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 6379
